TAGS:
  CostCenter: NO PROGRAM / 000000

NEPTUNE:
  engine_version: "1.3.2.1"
  backup_retention_days: 7
  preferred_backup_window: "03:00-04:00"
  preferred_maintenance_window: "sun:04:00-sun:05:00"
  deletion_protection: true
  cloudwatch_logs_exports:
    - "audit"
    - "slowquery"
  iam_auth_enabled: true
  storage_encrypted: true
  auto_minor_version_upgrade: true
  create_parameter_group: false
  parameter_group_parameters: {}

NEPTUNE_SAGEMAKER:
  domain_name: "sage-brain-studio"
